# Generated by Django 4.1.7 on 2023-03-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=25)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_operacao', models.CharField(max_length=25)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalado', models.IntegerField()),
                ('substituto', models.IntegerField()),
                ('data_permuta', models.DateField()),
                ('data_criacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('maticula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('data_pedido', models.DateField()),
                ('data_criacao', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lotacao', models.CharField(max_length=25)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
            ],
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_falta', models.DateField()),
                ('data_criacao', models.DateField(auto_now=True)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
            ],
        ),
        migrations.CreateModel(
            name='EscOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30)),
                ('data_operacao', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('roteiro', models.CharField(max_length=5)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.local')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.operacao')),
            ],
        ),
        migrations.CreateModel(
            name='EscMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30)),
                ('data_mensal', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('equipamento', models.CharField(max_length=20)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.local')),
                ('lotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.lotacao')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
            ],
        ),
    ]
