# Generated by Django 4.1.7 on 2023-05-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=25)),
                ('desc', models.TextField(max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_op', models.CharField(max_length=25)),
                ('dt_op', models.TextField()),
                ('co_g', models.TextField()),
                ('co', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('mat', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EscOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=30)),
                ('h_in', models.TimeField()),
                ('h_out', models.TimeField()),
                ('eqp', models.CharField(max_length=10)),
                ('road_map', models.CharField(max_length=5)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.area')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.local')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.operacao')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores'),
        ),
    ]
