# Generated by Django 4.1.7 on 2023-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='co',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='co_g',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='dt_op',
            field=models.DateField(),
        ),
    ]
