# Generated by Django 4.1.7 on 2023-05-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0002_alter_operacao_co_alter_operacao_co_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coo', to='sefit.servidores'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='co_g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coo_general', to='sefit.servidores'),
        ),
    ]
