# Generated by Django 4.1.7 on 2023-06-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0003_alter_local_desc_alter_servidores_admissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=25)),
                ('start', models.DateField(auto_now=True)),
                ('end', models.DateField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores')),
            ],
        ),
    ]
