# Generated by Django 4.1.7 on 2023-05-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0003_alter_escoperacao_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escoperacao',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores'),
        ),
    ]
