# Generated by Django 4.1.7 on 2023-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0004_afastamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamentos',
            name='end',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='afastamentos',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
