# Generated by Django 4.1.7 on 2023-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0005_alter_afastamentos_end_alter_afastamentos_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamentos',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='afastamentos',
            name='start',
            field=models.DateField(),
        ),
    ]
